import {Building,EmergencyFacility,Hazard,Waypoint,RouteEdge,NavigationSession} from '../models/models.js';import {AppError} from '../middleware/errorHandler.js';import {findSafestRoute} from '../services/routeEngine.js';import {parseIntent} from '../services/aiService.js';import {predictRisk} from '../services/mlService.js';
export async function buildings(req,res){res.json({success:true,data:await Building.find().sort('name')})}
export async function locations(req,res){const q=req.query.buildingId?{buildingId:req.query.buildingId}:{};res.json({success:true,data:await Waypoint.find(q).sort('name')})}
export async function facilities(req,res){const q={};if(req.query.buildingId)q.buildingId=req.query.buildingId;if(req.query.type)q.type=req.query.type;res.json({success:true,data:await EmergencyFacility.find(q).populate('waypointId').sort('name')})}
export async function hazards(req,res){const q={};if(req.query.buildingId)q.buildingId=req.query.buildingId;if(req.query.active!==undefined)q.active=req.query.active==='true';res.json({success:true,data:await Hazard.find(q).populate('reportedBy','name email').sort('-createdAt')})}
export async function createHazard(req,res){const h=await Hazard.create({...req.body,reportedBy:req.user.sub});req.app.get('io').emit('HAZARD_CREATED',h);res.status(201).json({success:true,data:h})}
export async function updateHazard(req,res){const h=await Hazard.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!h)throw new AppError(404,'HAZARD_NOT_FOUND','Hazard not found');req.app.get('io').emit('HAZARD_UPDATED',h);req.app.get('io').emit('ROUTE_INVALIDATED',{buildingId:h.buildingId,reason:'Hazard updated'});res.json({success:true,data:h})}
export async function deleteHazard(req,res){const h=await Hazard.findByIdAndDelete(req.params.id);if(!h)throw new AppError(404,'HAZARD_NOT_FOUND','Hazard not found');req.app.get('io').emit('HAZARD_REMOVED',{id:req.params.id,buildingId:h.buildingId});res.json({success:true,data:{id:req.params.id}})}
export async function calculateRoute(req,res){const {buildingId,startWaypointId,facilityType='EXIT',avoidStairs=false,accessibilityRequired=false}=req.body;if(!buildingId||!startWaypointId)throw new AppError(400,'VALIDATION_ERROR','buildingId and startWaypointId are required');const [waypoints,edges,hazards,facilities]=await Promise.all([Waypoint.find({buildingId}),RouteEdge.find({buildingId}),Hazard.find({buildingId,active:true}),EmergencyFacility.find({buildingId})]);const route=findSafestRoute({waypoints,edges,hazards,facilities,startWaypointId,facilityType,avoidStairs,accessibilityRequired});if(!route)throw new AppError(409,'NO_SAFE_ROUTE_AVAILABLE','No safe route is currently available');const risk=await predictRisk({distance:route.distance,crowdLevel:.15,hazardDistance:999,turns:Math.max(0,route.waypointIds.length-2),width:1.5,floor:0,stairCount:avoidStairs?0:1,historicalIncidents:0,blocked:false});res.json({success:true,data:{...route,risk,routeStatus:'CLEAR'}})}
export async function voiceIntent(req,res){if(!req.body?.text)throw new AppError(400,'VALIDATION_ERROR','text is required');res.json({success:true,data:await parseIntent(req.body.text)})}
export async function startNavigation(req,res){const s=await NavigationSession.create({userId:req.user.sub,...req.body});res.status(201).json({success:true,data:s})}
export async function health(req,res){res.json({success:true,data:{status:'ok',mongodb:req.app.get('mongoStatus')?'connected':'unavailable',mlService:process.env.ML_SERVICE_URL||'configured',environment:process.env.NODE_ENV||'development'}})}
